name: Targets Local Reusable Workflow Mutable Child

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: __FIXTURES_REPOSITORY__/composite-actions/local-reusable-workflow-target@main
