name: Targets Mixed First Party

on:
  workflow_dispatch:

jobs:
  mixed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/parent@upstream-PR/fix-recurse-into-local-reusable-workflows
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/leaf@3aa32f4195cfe2c317e08bf59720997b7cecf3b7
