name: Targets Mixed First Party

on:
  workflow_dispatch:

jobs:
  mixed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/parent@baseline/upstream-99004139
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/leaf@__FIXTURES_SHA__