name: Targets Local Reusable Workflow Immutable Child

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/local-reusable-workflow-target@3aa32f4195cfe2c317e08bf59720997b7cecf3b7
