name: Targets Unsupported

on:
  workflow_dispatch:

jobs:
  direct-protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.20

  remote-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/docker-unsupported@3aa32f4195cfe2c317e08bf59720997b7cecf3b7
