name: Targets Mutable

on:
  workflow_dispatch:

jobs:
  remote-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/parent@upstream-PR/chore-update-baseline-browser-mapping-and-audit-fixes

  remote-composite-duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/parent@upstream-PR/chore-update-baseline-browser-mapping-and-audit-fixes

  remote-reusable:
    uses: Wuodan/ensure-immutable-actions-test-custom-actions/.github/workflows/reusable.yml@upstream-PR/chore-update-baseline-browser-mapping-and-audit-fixes
