name: Targets Local Reusable Workflow Immutable Child

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/local-reusable-workflow-target@e33e5680483b49d17eab65de15b068edfbd2474b
