name: Targets Unsupported

on:
  workflow_dispatch:

jobs:
  direct-protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.20

  remote-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/docker-unsupported@63b1cf61055a58adbce3e8b7c638d6070e1eb544