name: Targets Mutable

on:
  workflow_dispatch:

jobs:
  remote-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/parent@main

  remote-composite-duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-custom-actions/composite-actions/parent@main

  remote-reusable:
    uses: Wuodan/ensure-immutable-actions-test-custom-actions/.github/workflows/reusable.yml@main

  local-reusable-workflow:
    uses: ./.github/workflows/targets-local-reusable-workflow-mutable-parent.yml
