name: Targets Local Reusable Workflow Immutable Child

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/local-reusable-workflow-target@__FIXTURES_SHA__
