name: Targets Immutable

on:
  workflow_dispatch:

jobs:
  remote-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: Wuodan/ensure-immutable-actions-test-fixtures/composite-actions/parent@__FIXTURES_SHA__

  remote-reusable:
    uses: Wuodan/ensure-immutable-actions-test-fixtures/.github/workflows/reusable-immutable.yml@__FIXTURES_SHA__

  local-reusable-workflow:
    uses: ./.github/workflows/targets-local-reusable-workflow-immutable-parent.yml
