name: Targets Unsupported

on:
  workflow_dispatch:

jobs:
  direct-protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.20

  remote-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: __FIXTURES_REPOSITORY__/composite-actions/docker-unsupported@64b6290f8d6f3adef61136543f43c6607d5b301e
