name: Validate Unsupported Refs

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ensure-immutable-actions against unsupported refs
        uses: Wuodan/ensure-immutable-actions@development
        with:
          github-token: ${{ github.token }}
          workflows: targets-unsupported.yml
          fail-on-mutable: false
